name: Docker Image CI

on:
  push:
    tags:
      - '**' # Push events to every tag including hierarchical tags like v1.0/beta

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Docker image reference
        id: set-image-ref
        run: echo "::set-output name=image-ref::docker.io/${{ secrets.DOCKER_HUB_REPOSITORY }}:${GITHUB_REF#refs/tags/}"
      - name: Build image from dockerfile
        run: |
          echo "${{ secrets.DOCKER_KEY }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin docker.io
          docker build . --file Dockerfile --tag "${{ steps.set-image-ref.outputs.image-ref }}"

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.set-image-ref.outputs.image-ref }}
          format: 'table'
          exit-code: '0' # Allow Trivy to exit with code 0 (success)
          ignore-unfixed: false
          vuln-type: 'os,library'
          severity: 'MEDIUM,CRITICAL,HIGH'

      - name: Push Docker image
        if: success()
        run: |
          docker push "${{ steps.set-image-ref.outputs.image-ref }}"
